TAKEOFF_ALTITUDE = 2.0

BEAM_COLORS = ["red", "blue", "pink", "black"]
FIRST_SIDE = "left"

LINE_DETECTION_SPACE = "hsv"
LINE_DETECTION_IMAGE_SOURCE = "webcam"
LINE_DETECTION_SHOW_VISUALIZATION = "false"
LINE_DETECT_NODE_NAME = "line_detector_process"
LINE_DETECTION_VISUALIZATION_TITLE = "Slalom Detection"

SEARCH_SPEED_Y = 0.3
SEARCH_TIMEOUT = 30.0

CENTERING_KP = 0.002
CENTERING_THRESHOLD = 20.0
CENTERING_TIMEOUT = 15.0
CENTERING_CONFIRMATIONS = 10

APPROACH_DISTANCE = 1.5
APPROACH_SPEED = 0.4
APPROACH_TIMEOUT = 20.0

SIDE_PASS_SPEED = 0.5
SIDE_PASS_TIME = 2.0
FORWARD_PASS_SPEED = 0.6
FORWARD_PASS_TIME = 3.0

IMAGE_CENTER_X = 320.0
IMAGE_CENTER_Y = 240.0

RETURN_ALTITUDE = 2.0
