TAKEOFF_ALTITUDE = 1.3

BEAM_COLORS = ["red_sl", "blue_sl", "pink_sl", "black_sl"]
FIRST_SIDE = "left"

LINE_DETECTION_SPACE = "hsv"
LINE_DETECTION_IMAGE_SOURCE = "webcam"
LINE_DETECTION_SHOW_VISUALIZATION = "false"
LINE_DETECT_NODE_NAME = "line_detector_process"
LINE_DETECTION_VISUALIZATION_TITLE = "Slalom Detection"
LINE_DETECTION_METHOD="RotatedRect"

SEARCH_SPEED_Y = 0.6
SEARCH_TIMEOUT = 20.0

CENTERING_KP = 0.0017
CENTERING_THRESHOLD = 29.8
CENTERING_TIMEOUT = 20.0
CENTERING_CONFIRMATIONS = 15

APPROACH_DISTANCE = 1.56
APPROACH_SPEED = 0.32
APPROACH_TIMEOUT = 13.0

SIDE_PASS_SPEED = 0.6
SIDE_PASS_TIME = 2.5
FORWARD_PASS_SPEED = 0.62
FORWARD_PASS_TIME = 3.4

IMAGE_CENTER_X = 320.0
IMAGE_CENTER_Y = 240.0

RETURN_ALTITUDE = 2.0
