"""
Distance estimation model parameters for hook operation.
This file is automatically generated by distance_models.py.
Manual changes to this file may be overwritten.
"""

# Best model according to AIC: Polynomial Degree 4
# AIC: 104.34, R²: 0.9955, RMSE: 5.39 cm

# -- Linear model constant --
DISTANCE_CALIBRATION_CONST = 5900.0  # cm*px (linear model k)

# -- Exponential model parameters --
DISTANCE_EXP_A = 1054.256793  # Amplitude
DISTANCE_EXP_B = 0.050442  # Decay rate
DISTANCE_EXP_C = 47.392873  # Offset

# -- Polynomial model coefficients --
# Format: [a4, a3, a2, b, c] for a4x^4 + a3x^3 + a2x^2 + bx + c
DISTANCE_POLY_COEFFS = [
    7.197919144961594e-06,
    -0.0030956983776919693,
    0.48095833679757577,
    -32.72919438874427,
    906.2831567777,
]

# -- Logarithmic model parameters --
DISTANCE_LOG_A = -160.029127  # Coefficient
DISTANCE_LOG_B = 790.059325  # Offset

# -- Inverse Power model parameters --
DISTANCE_K = 10000.0000  # Coefficient
DISTANCE_P = 1.0731  # Power

# -- Robust Polynomial Degree 2 model parameters --
DISTANCE_ROBUST_A = -0.038715  # x² coefficient
DISTANCE_ROBUST_B = 5.343342  # x coefficient  
DISTANCE_ROBUST_C = 0.162265  # constant term

# -- Target parameters --
TARGET_DISTANCE_CM = 20.0      # Target distance from hose in cm
DISTANCE_TOLERANCE_CM = 2.0    # Tolerance for distance estimation